// Generated by CoffeeScript 1.10.0
(function() {
  var failedValidationName, logger, nameOptions, passedValidationName, printName, sop, validateName, values, vorpal, vorpalLog, vorpalSOP;

  vorpal = (require('vorpal'))();

  vorpalLog = require('vorpal-log');

  vorpalSOP = require('../index');

  vorpal.use(vorpalLog).use(vorpalSOP).delimiter('vorpal-setorprint demo $').show();

  logger = vorpal.logger;

  sop = vorpal.sop;

  values = {
    greeting: 'Hello',
    name: 'Franz Foobert'
  };

  sop.command('greeting', values).alias('foobar');

  validateName = function(arg) {
    if (arg.match(/\d/) === null) {
      return arg;
    } else {
      return null;
    }
  };

  printName = function(arg) {
    return logger.info("Your name seems to be " + arg + ", am I right?");
  };

  failedValidationName = function(key, arg) {
    return logger.error("A real " + key + " doesn\'t contain digits! I bet " + arg + " isn\'t even your real name.");
  };

  passedValidationName = function(key, arg, value) {
    return logger.confirm(value + "? Well, that\'s a splendid " + key + ".");
  };

  nameOptions = {
    validate: validateName,
    print: printName,
    description: 'prints or sets the name, with a custom description',
    failedValidation: failedValidationName,
    passedValidation: passedValidationName
  };

  sop.command('name', values, nameOptions);

  vorpal.command('greet').description('a complex command to greet the user').action(function(args, cb) {
    logger.log(values.greeting + ", " + values.name + ".");
    return cb();
  });

  logger.printMsg('');

  logger.info('This is a demo program for the vorpal-log extension.');

  logger.info('Run help to see what vorpal-setorprint added');

}).call(this);
